import 'flowbite/dist/flowbite.css';
import './global.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Welcome to quick-learn-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={true}
          pauseOnFocusLoss={false}
        />
        {children}
      </body>
    </html>
  );
}
