name: Test

on:
  pull_request_target:
    branches: [dev]

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create env file
      run: |
        touch apps/quick-learn-frontend-e2e/.env
        echo "QLDEV_BASE_URL=${{ secrets.QLDEV_BASE_URL }}" >> apps/quick-learn-frontend-e2e/.env

    - name: Install dependencies
      run: npm ci

    - name: Reset Nx cache
      run: npx nx reset

    - name: Run test
      run: npx nx run quick-learn-frontend-e2e:e2e
