export enum RouteEnum {
  LOGIN = '/',
  RESET_PASSWORD = '/reset-password',
  FORGOT_PASSWORD = '/forgot-password',
  DASHBOARD = '/dashboard',
  TEAM = '/dashboard/teams',
  TEAM_EDIT = '/dashboard/teams/edit',
  MY_LEARNING_PATH = '/dashboard/learning-path',
  PROFILE_SETTINGS = '/dashboard/profile-settings',
  CHANGE_PASSWORD = '/dashboard/profile-settings/change-password',
  EMAIL_PREFERENCE = '/dashboard/profile-settings/email-preference',
  ACCOUNT_SETTINGS = '/dashboard/account-settings',
  PRIMARY_SKILLS = '/dashboard/account-settings/primary-skills',
  ROADMAP_CATEGORIES = '/dashboard/account-settings/roadmap-categories',
  COURSES_CATEGORIES = '/dashboard/account-settings/courses-categories',
  CONTENT = '/dashboard/content',
  APPROVALS = '/dashboard/approvals',
  COMMUNITY = '/dashboard/community',
  ARCHIVE = '/dashboard/archive',
}
