export enum RouteEnum {
  LOGIN = '/',
  RESET_PASSWORD = '/reset-password',
  FORGOT_PASSWORD = '/forgot-password',
  DAILY_LESSONS = '/daily-lesson',
  DASHBOARD = '/dashboard',
  TEAM = '/dashboard/teams',
  TEAM_EDIT = '/dashboard/teams/edit',
  MY_LEARNING_PATH = '/dashboard/learning-path',
  PROFILE_SETTINGS = '/dashboard/profile-settings',
  CHANGE_PASSWORD = '/dashboard/profile-settings/change-password',
  EMAIL_PREFERENCE = '/dashboard/profile-settings/email-preference',
  ACCOUNT_SETTINGS = '/dashboard/account-settings',
  PRIMARY_SKILLS = '/dashboard/account-settings/primary-skills',
  ROADMAP_CATEGORIES = '/dashboard/account-settings/roadmap-categories',
  COURSES_CATEGORIES = '/dashboard/account-settings/courses-categories',
  CONTENT = '/dashboard/content',
  APPROVALS = '/dashboard/approvals',
  FLAGGED = '/dashboard/flagged',
  COMMUNITY = '/dashboard/community',
  ARCHIVED_USERS = '/dashboard/archived/users',
  ARCHIVED_ROADMAPS = '/dashboard/archived/roadmaps',
  ARCHIVED_COURSES = '/dashboard/archived/courses',
  ARCHIVED_LESSONS = '/dashboard/archived/lessons',
  CHANGE_LOGS = 'https://release.quicklabs.in/quick-learn/changelogs',
  FEATURE_LOGS = 'https://release.quicklabs.in/quick-learn/roadmap',
  LEADERBOARD = '/dashboard/leaderboard',
}
